name: package

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libarchive-tools dpkg-dev
          
      - name: Build arm64
        run: |
          rm -rf ./bbdown*/
          export version=$(curl -s https://api.github.com/repos/nilaoda/BBDown/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          mkdir bbdown-base
          mkdir -p bbdown-base/DEBIAN
          mkdir -p bbdown-base/usr/bin
          curl -s https://api.github.com/repos/nilaoda/BBDown/releases/latest \
            | grep browser_download_url \
            | grep 'linux-arm64' \
            | cut -d '"' -f 4 \
            | xargs -n 1 curl -L -o bbdown.zip
          unzip bbdown.zip
          chmod +x BBDown
          mv BBDown bbdown-base/usr/bin/bbdown
          ln -s bbdown-base/usr/bin/bbdown bbdown-base/usr/bin/BBDown
          wget https://raw.githubusercontent.com/hmsjy2017/bbdown-debs/main/controltemplate -O bbdown-base/DEBIAN/control
          sed -i "s/VTR/$version/" bbdown-base/DEBIAN/control
          chmod 755 bbdown-base/DEBIAN/*
          dpkg-deb -b ./bbdown-base bbdown_"$version"_arm64.deb

      - name: Create symlinks
        run: |
          rm -rf ./bbdown*/
          export version=$(curl -s https://api.github.com/repos/nilaoda/BBDown/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          rm -rf ./*latest.deb
          ln -fs "$(find . -name '*arm64.deb' -type f -printf '%P\n' -quit)" bbdown-arm64-latest.deb

      - name: Upload
        run: |
          rm -rf ./bbdown*/
          export version=$(curl -s https://api.github.com/repos/nilaoda/BBDown/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          echo $version > current.txt
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload bbdown v$(curl -s https://api.github.com/repos/nilaoda/BBDown/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')" 
          git push
